### ISSUE TITLE
Upgrade to 29.0.1

### ISSUE THREAD

**Issue by jreyeshdez** [arm64-compat/apache-druid#9]

**Comment by altaiezior** [comment]
@jreyeshdez should I build it or do you want to submit a merge request?

**Comment by jreyeshdez** [comment]
@anuragagarwal561994 I would not mind doing it however I am not sure what the procedure you follow to build it. If you have spare time to build it or if you can some readme with instructions to build it as I actively use this repo for our dev/prod clusters.

**Comment by altaiezior** [comment]
@jreyeshdez mostly it is simple, you just have to create a branch go to the sub-module, update the tag and push the commit.

Mainly the issue is the circle-ci pipeline I think needs permission to run, hence I have only created the merge request for the same. Usually since it is a java repo nothing breaks and it builds without any issues, but at times more changes can be required.

When the branch gets merged, it builds and pushes the release images.

**Comment by jreyeshdez** [comment]
Thanks @anuragagarwal561994 , will attempt next time then.

**Comment by altaiezior** [comment]
Easy Peasy, image will be published in 15-20 mins
